/* =========================================================
   Takashi Yoshinaga — Portfolio 2026
   Vanilla JS — no framework
   ========================================================= */

(() => {
  "use strict";

  /* ---------------------------------------------------
     Data: Hobby prototypes
     --------------------------------------------------- */
  const HOBBY = [
    { id: "57gkK-xGxKQ", t: "Snap2VoxelAR",
      d: "Turns a quick real-world capture into voxel-style 3D content and brings it back into the room as an AR object — a playful bridge between physical snapshots and editable spatial blocks.", tags: ["ar", "ai"] },
    { id: "5nlFjTWZSE8", t: "Turn Your Memories into 3D Gaussian Splatting",
      d: "Transforms personal memories into a 3D Gaussian Splatting scene, letting captured moments become navigable volumetric spaces for XR viewing and spatial storytelling.", tags: ["ai", "ar"] },
    { id: "ZE_F2NsOSfQ", t: "Project HoloBox",
      d: "Achieves a 3D perspective effect on an iPad without a dedicated display, and lets the virtual world inside the iPad interact with HoloLens 2 and other AR devices.", tags: ["ar", "vr"] },
    { id: "JnxXkK8pQ2Q", t: "Reality Portal",
      d: "Syncs a real-world door with its virtual portal representation. By aligning physical and virtual objects, the prototype explores more immersive mixed-reality experiences.", tags: ["vr", "sensor"] },
    { id: "aFJR6CnUeqs", t: "StickAR",
      d: "A Quest app that captures any visible text — handwritten or on screen — and turns it into a hand-grabbable AR sticky note. Toss the note at a real PC monitor to paste the recognized text into the active window.", tags: ["vr", "ai"] },
    { id: "dkM1WFAXtDg", t: "Real-World Lighting",
      d: "Reflects real-world lighting conditions on Meta Quest. Position and shape data of real objects is streamed to the Quest via WebSocket or WebRTC.", tags: ["vr", "sensor"] },
    { id: "525E8wxZyxM", t: "Shake-to-Send",
      d: "A shake gesture detected by a smartphone's accelerometer triggers sending 2D/3D images to HoloLens. Inspired by interfaces from SF movies.", tags: ["ar", "sensor"] },
    { id: "j2GieSCbeIg", t: "HoloTuberKit",
      d: "Broadcasts point clouds over the internet and visualizes them on XR devices. Viewer apps for HoloLens, Nreal Light, Meta Quest and ARCore — available on GitHub.", tags: ["ar", "sensor"] },
    { id: "zSK1FuUiQSo", t: "Volumetric Telepresence",
      d: "Remote communication based on volumetric video streaming. Users meet remotely while sharing and manipulating 2D images, videos, and 3D models.", tags: ["ar", "vr"] },
    { id: "vZnM_0YjJ24", t: "AR Fireworks",
      d: "An iPad is used as a controller to place the fireworks origin in real space; HoloLens 2 is the AR viewer. Lets users intuitively place and experience fireworks in their environment.", tags: ["ar"] },
    { id: "YgYVepT3xEs", t: "Depth Masked Spray",
      d: "Uses Meta Quest 3's depth data so real-world objects act as masks for virtual spray painting — spray patterns respect physical shape and position.", tags: ["vr", "sensor"] },
    { id: "vnuHLrYknt0", t: "Mobile Scan to XR",
      d: "Transfers 3D objects scanned by a smartphone to XR devices, enabling sharing of 3D objects with people in remote locations as long as there is an internet connection.", tags: ["ar"] },
    { id: "Jb8YrRuD168", t: "Finger Frame Window",
      d: "Sees a remote environment through a finger frame. Leap Motion detects the gesture and adjusts the size of an AR window displayed on Meta 2.", tags: ["ar", "sensor"] },
    { id: "kau5hRnEGdI", t: "DejaViewer",
      d: "Uses Meta Quest 3's depth data and color camera input to instantly record and replay the shape and motion of objects in front of the user.", tags: ["vr", "sensor"] },
    { id: "CICZqMf9QwA", t: "Half-Mirror AR",
      d: "A test of half-mirror AR with hand–character interaction. This style of AR makes it easier — especially for children — to experience optical see-through AR without wearing an HMD.", tags: ["ar"] },
    { id: "7-Z8c2pjJQc", t: "Spatial Clipper",
      d: "Extracts a spatial mesh within a clipping sphere and can transmit it to other devices — enabling hands-free scanning and sharing of geometry with remote users.", tags: ["ar", "sensor"] },
    { id: "K34p7RwjWt0", t: "EMG AR Shooter",
      d: "An AR shooter using HoloLens 2 and an EMG sensor. A virtual bullet fires when the user strongly clenches their hand — enabling interactions that pure image processing cannot.", tags: ["ar", "sensor"] },
    { id: "brWvzuRAXgU", t: "Wall Touch Panel",
      d: "Turns a flat wall into a touch panel using depth and image processing. Demonstrates a virtual peephole that lets users look into the next room via a web camera.", tags: ["sensor", "ar"] },
    { id: "b02gry-nvyM", t: "ChatGPT × AR",
      d: "3D objects generated by ChatGPT are displayed in AR. Instead of a virtual keyboard, AI-based character recognition is used for prompt input — enabling more intuitive interaction.", tags: ["ai", "ar"] },
    { id: "8ZfWHPwKC5c", t: "Multi-User AR",
      d: "Shares an AR experience across multiple users and devices. Both virtual objects and user operations are synchronized between HoloLens users and a recording smartphone.", tags: ["ar"] },
    { id: "qXd_yPjMYoU", t: "Real-time AR Coloring",
      d: "Recognizes a square frame to clip the coloring area, then visualizes the textured object on AR devices. Works on HoloLens, ARCore devices, Aryzon, and Looking Glass.", tags: ["ar"] },
    { id: "KpenTQ6t6-g", t: "LiDAR Spatial Sync",
      d: "Scans the environment with iPad/iPhone LiDAR and links real and virtual worlds — an avatar from the virtual side appears in the real room, and object placement is synced both ways.", tags: ["sensor", "ar"] }
  ];

  /* ---------------------------------------------------
     Data: GitHub repos
     --------------------------------------------------- */
  const REPOS = [
    { name: "360-to-RealityScan",               d: "Converts 360-degree imagery into assets that can be used with Apple's RealityScan workflow." },
    { name: "MetaXR-SDK-Samples",               d: "Sample projects for building and testing XR interactions with the Meta XR SDK." },
    { name: "QuestArUcoMarkerTracking",         d: "Unity sample for recognising ArUco markers on Meta Quest." },
    { name: "iPhoneCinematicDepthTo3D",          d: "Generates 3D content from depth data captured in iPhone's Cinematic mode." },
    { name: "GeospatialAPI-Unity-StarterKit",    d: "Starter kit for Google ARCore Geospatial API in Unity." },
    { name: "babylonjs-webxr",                   d: "Sample set for working with WebXR using Babylon.js." },
    { name: "MRTK-Profiles-for-NrealLight",      d: "MRTK profiles tuned for Nreal Light." },
    { name: "iPad-LiDAR-Depth-Sample-for-Unity", d: "Sample for accessing iPad LiDAR depth data from Unity." },
    { name: "Azure-Kinect-Sample-for-Unity",     d: "Sample for using Azure Kinect with Unity." },
    { name: "webxr-hand-tracking-sample",        d: "WebXR hand-tracking sample." },
    { name: "Oculus-Quest-Interaction-Sample",   d: "Interaction sample for Oculus Quest." },
    { name: "Oculus-Quest-Input-Sample",         d: "Input sample for Oculus Quest." }
  ];
  /* ---------------------------------------------------
     Header scroll state
     --------------------------------------------------- */
  const header = document.getElementById("site-header");
  const onScroll = () => {
    if (!header) return;
    header.classList.toggle("is-scrolled", window.scrollY > 8);
  };
  window.addEventListener("scroll", onScroll, { passive: true });
  onScroll();
  /* ---------------------------------------------------
     Mobile menu
     --------------------------------------------------- */
  const menuBtn = document.getElementById("menu-btn");
  const mobileMenu = document.getElementById("mobile-menu");
  function setMenu(open) {
    if (!menuBtn || !mobileMenu) return;
    menuBtn.setAttribute("aria-expanded", open ? "true" : "false");
    if (open) {
      mobileMenu.hidden = false;
      // next frame for transition
      requestAnimationFrame(() => mobileMenu.classList.add("is-open"));
      document.body.style.overflow = "hidden";
    } else {
      mobileMenu.classList.remove("is-open");
      document.body.style.overflow = "";
      // hide after transition
      setTimeout(() => { mobileMenu.hidden = true; }, 320);
    }
  }
  if (menuBtn) menuBtn.addEventListener("click", () => {
    setMenu(menuBtn.getAttribute("aria-expanded") !== "true");
  });
  if (mobileMenu) mobileMenu.addEventListener("click", (e) => {
    const target = e.target;
    if (target instanceof HTMLElement && target.closest("a")) setMenu(false);
  });

  /* ---------------------------------------------------
     Works accordion
     --------------------------------------------------- */
  const accordionRoot = document.getElementById("works-accordion");
  if (accordionRoot) {
    const triggers = Array.from(accordionRoot.querySelectorAll(".genre__trigger"));
    const prefersReduced = window.matchMedia("(prefers-reduced-motion: reduce)").matches;

    function getPanel(trigger) {
      return document.getElementById(trigger.getAttribute("aria-controls"));
    }

    function openItem(trigger) {
      const panel = getPanel(trigger);
      if (!panel) return;
      trigger.setAttribute("aria-expanded", "true");
      trigger.closest(".genre")?.classList.add("is-open");
      panel.hidden = false;
      panel.querySelectorAll(".work-card").forEach((c) => c.classList.add("is-in"));

      if (prefersReduced) {
        panel.style.height = "auto";
        return;
      }

      const targetH = panel.scrollHeight;
      panel.style.height = "0px";
      void panel.offsetHeight;
      panel.style.height = targetH + "px";

      const onEnd = (e) => {
        if (e.propertyName !== "height") return;
        panel.style.height = "auto";
        panel.removeEventListener("transitionend", onEnd);
      };
      panel.addEventListener("transitionend", onEnd);
    }

    function closeItem(trigger) {
      const panel = getPanel(trigger);
      if (!panel) return;
      trigger.setAttribute("aria-expanded", "false");
      trigger.closest(".genre")?.classList.remove("is-open");

      if (prefersReduced) {
        panel.hidden = true;
        panel.style.height = "";
        return;
      }

      panel.style.height = panel.scrollHeight + "px";
      void panel.offsetHeight;
      panel.style.height = "0px";

      const onEnd = (e) => {
        if (e.propertyName !== "height") return;
        panel.hidden = true;
        panel.style.height = "";
        panel.removeEventListener("transitionend", onEnd);
      };
      panel.addEventListener("transitionend", onEnd);
    }

    function activateOnly(trigger) {
      const isOpen = trigger.getAttribute("aria-expanded") === "true";
      if (isOpen) {
        closeItem(trigger);
        return;
      }
      triggers.forEach((t) => {
        if (t === trigger) openItem(t);
        else if (t.getAttribute("aria-expanded") === "true") closeItem(t);
      });
    }

    triggers.forEach((trigger) => {
      trigger.addEventListener("click", () => activateOnly(trigger));
      trigger.addEventListener("keydown", (e) => {
        const idx = triggers.indexOf(trigger);
        let next = -1;
        if (e.key === "ArrowDown") next = (idx + 1) % triggers.length;
        else if (e.key === "ArrowUp") next = (idx - 1 + triggers.length) % triggers.length;
        else if (e.key === "Home") next = 0;
        else if (e.key === "End") next = triggers.length - 1;
        if (next >= 0) { e.preventDefault(); triggers[next].focus(); }
      });
    });
  }

  /* ---------------------------------------------------
     Render Hobby grid
     --------------------------------------------------- */
  const FEATURED_COUNT = 8;
  const hobbyGrid = document.getElementById("hobby-grid");
  const hobbyMore = document.getElementById("hobby-more");
  let isHobbyExpanded = false;

  function renderHobby() {
    if (!hobbyGrid) return;
    const items = isHobbyExpanded ? HOBBY : HOBBY.slice(0, FEATURED_COUNT);
    hobbyGrid.innerHTML = items.map((it, idx) => {
      const num = String(HOBBY.indexOf(it) + 1).padStart(2, "0");
      return `
        <li>
          <button class="hobby-card" type="button" data-id="${it.id}"
            aria-label="${it.t}">
            <div class="hobby-card__thumb" style="background-image:url('https://img.youtube.com/vi/${it.id}/hqdefault.jpg')">
              <span class="hobby-card__num">${num}</span>
              <span class="hobby-card__play" aria-hidden="true">
                <svg viewBox="0 0 24 24"><path d="M8 5v14l11-7z" fill="currentColor"/></svg>
              </span>
            </div>
            <div class="hobby-card__body">
              <h3 class="hobby-card__title">${escapeHtml(it.t)}</h3>
              <p class="hobby-card__desc">${escapeHtml(it.d)}</p>
            </div>
          </button>
        </li>`;
    }).join("");

    // Bind click → modal
    hobbyGrid.querySelectorAll(".hobby-card").forEach((card) => {
      card.addEventListener("click", () => openModalFor(card.dataset.id));
    });

    // re-observe for fade-in
    hobbyGrid.querySelectorAll("li").forEach((li) => {
      li.classList.add("fade-in");
      observer && observer.observe(li);
    });

    if (hobbyMore) {
      const label = hobbyMore.querySelector("span");
      const icon = hobbyMore.querySelector("svg path");
      hobbyMore.hidden = HOBBY.length <= FEATURED_COUNT;
      hobbyMore.setAttribute("aria-expanded", isHobbyExpanded ? "true" : "false");
      if (label) label.textContent = isHobbyExpanded ? "Less" : "More";
      if (icon) icon.setAttribute("d", isHobbyExpanded ? "M5 12h14" : "M12 5v14M5 12h14");
    }
  }
  if (hobbyMore) hobbyMore.addEventListener("click", () => {
    isHobbyExpanded = !isHobbyExpanded;
    renderHobby();
    if (!isHobbyExpanded) {
      document.getElementById("hobby")?.scrollIntoView({ behavior: "smooth", block: "start" });
    }
  });

  /* ---------------------------------------------------
     Render GitHub repos
     --------------------------------------------------- */
  const repoGrid = document.getElementById("repo-grid");
  function renderRepos() {
    if (!repoGrid) return;
    repoGrid.innerHTML = REPOS.map((r) => {
      const href = `https://github.com/TakashiYoshinaga/${r.name}`;
      return `
        <li>
          <a class="repo-card" href="${href}" target="_blank" rel="noopener">
            <div class="repo-card__head">
              <span class="repo-card__icon" aria-hidden="true">
                <svg width="18" height="18" viewBox="0 0 24 24">
                  <path fill="currentColor" d="M12 .5C5.65.5.5 5.65.5 12c0 5.08 3.29 9.39 7.86 10.91.58.11.79-.25.79-.55v-2.16c-3.2.69-3.88-1.36-3.88-1.36-.52-1.34-1.28-1.69-1.28-1.69-1.05-.71.08-.7.08-.7 1.16.08 1.77 1.19 1.77 1.19 1.03 1.76 2.7 1.25 3.36.96.1-.75.4-1.25.73-1.54-2.55-.29-5.23-1.27-5.23-5.66 0-1.25.45-2.27 1.18-3.07-.12-.29-.51-1.46.11-3.04 0 0 .97-.31 3.18 1.17a11 11 0 0 1 5.78 0c2.21-1.48 3.18-1.17 3.18-1.17.62 1.58.23 2.75.11 3.04.74.8 1.18 1.82 1.18 3.07 0 4.4-2.69 5.37-5.25 5.65.41.36.78 1.05.78 2.12v3.14c0 .3.21.66.8.55C20.21 21.39 23.5 17.08 23.5 12 23.5 5.65 18.35.5 12 .5z"/>
                </svg>
              </span>
              <span class="repo-card__name">${r.name}</span>
            </div>
            <p class="repo-card__desc">${escapeHtml(r.d)}</p>
            <div class="repo-card__foot">
              <span>View on GitHub</span>
              <span class="repo-card__cta">
                <svg width="14" height="14" viewBox="0 0 24 24" aria-hidden="true"><path d="M7 17L17 7M9 7h8v8" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>
              </span>
            </div>
          </a>
        </li>`;
    }).join("");
    repoGrid.querySelectorAll("li").forEach((li) => {
      li.classList.add("fade-in");
      observer && observer.observe(li);
    });
  }

  /* ---------------------------------------------------
     Modal
     --------------------------------------------------- */
  const modal = document.getElementById("modal");
  const modalMedia = document.getElementById("modal-media");
  const modalTitle = document.getElementById("modal-title");
  const modalDesc = document.getElementById("modal-desc");
  const modalEyebrow = document.getElementById("modal-eyebrow");
  const modalYt = document.getElementById("modal-yt");
  let lastFocus = null;

  function openModalFor(videoId) {
    const it = HOBBY.find((h) => h.id === videoId);
    if (!it || !modal) return;
    modalTitle.textContent = it.t;
    modalDesc.textContent = it.d;
    modalEyebrow.textContent = "Prototype";
    modalYt.href = `https://www.youtube.com/watch?v=${videoId}`;
    modalMedia.innerHTML = `<iframe src="https://www.youtube-nocookie.com/embed/${videoId}?autoplay=1&rel=0" title="${escapeHtml(it.t)}" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>`;
    lastFocus = document.activeElement;
    modal.hidden = false;
    requestAnimationFrame(() => modal.setAttribute("aria-hidden", "false"));
    document.body.style.overflow = "hidden";
    const closeBtn = modal.querySelector(".modal__close");
    if (closeBtn) closeBtn.focus();
  }

  function closeModal() {
    if (!modal) return;
    modal.setAttribute("aria-hidden", "true");
    document.body.style.overflow = "";
    setTimeout(() => {
      modal.hidden = true;
      if (modalMedia) modalMedia.innerHTML = "";
      if (lastFocus && typeof lastFocus.focus === "function") lastFocus.focus();
    }, 250);
  }

  if (modal) {
    modal.querySelectorAll("[data-modal-close]").forEach((el) =>
      el.addEventListener("click", closeModal)
    );
    document.addEventListener("keydown", (e) => {
      if (e.key === "Escape" && modal.getAttribute("aria-hidden") === "false") closeModal();
    });
  }

  /* ---------------------------------------------------
     Lazy-load YouTube in Works tab on click
     --------------------------------------------------- */
  document.querySelectorAll(".yt-embed").forEach((el) => {
    const vid = el.dataset.vid;
    const title = el.dataset.title || "video";
    if (!vid) return;
    el.style.backgroundImage = `url('https://img.youtube.com/vi/${vid}/hqdefault.jpg')`;
    el.setAttribute("role", "button");
    el.setAttribute("tabindex", "0");
    el.setAttribute("aria-label", `Play video: ${title}`);
    const activate = () => {
      const iframe = document.createElement("iframe");
      iframe.src = `https://www.youtube-nocookie.com/embed/${vid}?autoplay=1&rel=0`;
      iframe.title = title;
      iframe.allow = "accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture";
      iframe.setAttribute("allowfullscreen", "");
      el.replaceWith(iframe);
    };
    el.addEventListener("click", activate);
    el.addEventListener("keydown", (e) => {
      if (e.key === "Enter" || e.key === " ") { e.preventDefault(); activate(); }
    });
  });

  /* ---------------------------------------------------
     IntersectionObserver — fade in
     --------------------------------------------------- */
  let observer;
  if ("IntersectionObserver" in window) {
    observer = new IntersectionObserver((entries) => {
      entries.forEach((entry) => {
        if (entry.isIntersecting) {
          entry.target.classList.add("is-in");
          observer.unobserve(entry.target);
        }
      });
    }, { rootMargin: "0px 0px -10% 0px", threshold: 0.1 });
    document.querySelectorAll(".fade-in").forEach((el) => observer.observe(el));
  } else {
    document.querySelectorAll(".fade-in").forEach((el) => el.classList.add("is-in"));
  }

  /* ---------------------------------------------------
     Active nav link on scroll
     --------------------------------------------------- */
  const sections = ["about", "works", "hobby", "github"]
    .map((id) => document.getElementById(id))
    .filter(Boolean);
  const navLinks = Array.from(document.querySelectorAll('.site-nav__list a[href^="#"]'));
  function updateActiveLink() {
    const y = window.scrollY + window.innerHeight * 0.3;
    let activeId = null;
    for (const s of sections) {
      if (s.offsetTop <= y) activeId = s.id;
    }
    navLinks.forEach((a) => a.classList.toggle("is-active", a.getAttribute("href") === `#${activeId}`));
  }
  window.addEventListener("scroll", updateActiveLink, { passive: true });
  updateActiveLink();

  /* ---------------------------------------------------
     Init
     --------------------------------------------------- */
  function escapeHtml(s) {
    return String(s).replace(/[&<>"']/g, (c) => ({
      "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;"
    }[c]));
  }

  // Year in footer
  const yearEl = document.getElementById("year");
  if (yearEl) yearEl.textContent = String(new Date().getFullYear());
  renderHobby();
  renderRepos();
})();
